
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E8372DB4E861319F3911341ADD095645'
    
_lr_action_items = {'$end':([1,2,4,6,8,9,],[0,-1,-4,-2,-3,-5,]),'STAR':([1,2,4,6,7,8,9,],[4,-1,-4,4,4,4,-5,]),'RPAREN':([2,4,6,7,8,9,],[-1,-4,-2,9,-3,-5,]),'BAR':([1,2,4,6,7,8,9,],[5,-1,-4,-2,5,-3,-5,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,],[3,3,-1,3,-4,3,-2,3,-3,-5,]),'LETTER':([0,1,2,3,4,5,6,7,8,9,],[2,2,-1,2,-4,2,-2,2,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re':([0,1,3,5,6,7,8,],[1,6,7,8,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re","S'",1,None,None,None),
  ('re -> LETTER','re',1,'p_re_letter','Implementing_RE.py',42),
  ('re -> re re','re',2,'p_re_concat','Implementing_RE.py',45),
  ('re -> re BAR re','re',3,'p_re_bar','Implementing_RE.py',48),
  ('re -> re STAR','re',2,'p_re_star','Implementing_RE.py',51),
  ('re -> LPAREN re RPAREN','re',3,'p_re_paren','Implementing_RE.py',54),
]
