
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'B5FCD447698A3DDF9A9D9C55E40A6FF6'
    
_lr_action_items = {'$end':([1,3,4,5,6,7,9,11,12,13,14,15,16,17,18,],[0,-3,-9,-2,-4,-7,-9,-12,-1,-7,-5,-8,-10,-11,-6,]),'RPAREN':([3,5,6,7,8,11,13,14,15,17,18,],[-3,-2,-4,-7,15,-12,-7,-5,-8,-11,-6,]),'OR':([3,4,5,6,7,8,9,11,13,14,15,17,18,],[-3,10,-2,-4,-7,10,10,-12,-7,-5,-8,10,-6,]),'LPAREN':([0,2,3,4,5,6,7,9,10,11,13,14,15,17,18,],[2,2,-3,2,-2,-4,-7,2,2,-12,-7,-5,-8,-11,-6,]),'STAR':([3,4,5,6,7,8,9,11,13,14,15,17,18,],[-3,11,-2,-4,-7,11,11,-12,-7,-5,-8,11,-6,]),'LETTER':([0,2,3,4,5,6,7,9,10,11,13,14,15,17,18,],[7,7,-3,7,-2,-4,13,7,7,-12,13,-5,-8,-11,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re':([0,],[1,]),'exp':([0,2,4,9,10,],[4,8,9,9,17,]),'closedexp':([0,2,4,9,10,],[5,5,5,5,5,]),'orexp':([0,2,4,9,10,],[3,3,3,3,3,]),'starexp':([0,2,4,9,10,],[6,6,6,6,6,]),'exps':([4,9,],[12,16,]),'letters':([7,13,],[14,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re","S'",1,None,None,None),
  ('re -> exp exps','re',2,'p_RE','demo.py',32),
  ('exp -> closedexp','exp',1,'p_exp','demo.py',40),
  ('exp -> orexp','exp',1,'p_exp','demo.py',41),
  ('exp -> starexp','exp',1,'p_exp','demo.py',42),
  ('exp -> LETTER letters','exp',2,'p_exp_letter','demo.py',47),
  ('letters -> LETTER letters','letters',2,'p_str','demo.py',51),
  ('letters -> <empty>','letters',0,'p_str_e','demo.py',54),
  ('closedexp -> LPAREN exp RPAREN','closedexp',3,'p_closedexp','demo.py',62),
  ('exps -> <empty>','exps',0,'p_exps_empty','demo.py',66),
  ('exps -> exp exps','exps',2,'p_exps','demo.py',70),
  ('orexp -> exp OR exp','orexp',3,'p_orexp','demo.py',74),
  ('starexp -> exp STAR','starexp',2,'p_STAR','demo.py',80),
]
